spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:pairprogramming;NON_KEYWORDS=USER
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
      format_sql: true
logging.level:
  org.hibernate.SQL: debug
jwt:
  secret_key: c2VjcmV0LWtleXNlY3JldC1rZXlzZWNyZXQta2V5c2VjcmV0LWtleXNlY3JldC1rZXlzZWNyZXQta2V5c2VjcmV0LWtleQ==