--INSERT INTO MEMBER (MEMBER_ID, EMAIL, PASSWORD, NAME) VALUES (1, 'temp', 'temp', 'temp');

INSERT INTO PROBLEM (PROBLEM_ID, DESCRIPTION, RANK, RESTRICTION, TITLE, INPUT_OUTPUT_EXAMPLE) VALUES (1, 'Problem description text', 'LEVEL1', 'No restrictions', 'Problem Title', 'Input example: Output example');
INSERT INTO PROBLEM_STANDARD_FORMAT (PROBLEM_ID, PROBLEM_STANDARD_FORMAT_ID, LANGUAGE_TYPE, STANDARD_FORMAT)  VALUES (1, 1, 'java', 'Hello2');
INSERT INTO PROBLEM_STANDARD_FORMAT (PROBLEM_ID, PROBLEM_STANDARD_FORMAT_ID, LANGUAGE_TYPE, STANDARD_FORMAT)  VALUES (1, 2, 'python', 'Hello3');

INSERT INTO PROBLEM_TEST_CASE (PROBLEM_TEST_CASE_ID, INPUT, OUTPUT, PROBLEM_ID) VALUES (1, 'apple', 'elppa', 1);
INSERT INTO PROBLEM_TEST_CASE (PROBLEM_TEST_CASE_ID, INPUT, OUTPUT, PROBLEM_ID) VALUES (2, 'banana', 'ananab', 1);
INSERT INTO PROBLEM_TEST_CASE (PROBLEM_TEST_CASE_ID, INPUT, OUTPUT, PROBLEM_ID) VALUES (3, 'hello', 'olleh', 1);

